development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:c5c1d641cbd61588f853fd2995eda665@sole.redistogo.com:10424/
  channel_prefix: projecttracker_production
