development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:p178522aa270d53b8cca6bd126efccf0f6e2efa1d9a5b705b3be6248635bb9be7@ec2-107-22-230-192.compute-1.amazonaws.com:29129
  channel_prefix: projecttracker_production
